//---------------------------------------------------------------------------

#ifndef DataModuleUnitH
#define DataModuleUnitH
//---------------------------------------------------------------------------
#include <Classes.hpp>
#include <Controls.hpp>
#include <StdCtrls.hpp>
#include <Forms.hpp>
#include <DB.hpp>
#include <IBCustomDataSet.hpp>
#include <IBDatabase.hpp>
#include <IBTable.hpp>
#include <Menus.hpp>
#include <IBStoredProc.hpp>
#include <IBQuery.hpp>
//---------------------------------------------------------------------------
class TDM : public TDataModule
{
__published:	// IDE-managed Components
        TIBDatabase *DB;
        TIBTransaction *Transaction;
        TIBTable *RepairTBL;
        TDataSource *RepairDS;
        TMainMenu *MainMenu;
        TMenuItem *ImportExport1;
        TMenuItem *Export1;
        TMenuItem *Help1;
        TMenuItem *About1;
        TIBTable *EmployeeTBL;
        TDataSource *EmployeeDS;
        TIBTable *RShopTBL;
        TDataSource *RShopDS;
        TIBTable *VehicleTBL;
        TDataSource *VehicleDS;
        TMenuItem *Open1;
        TMenuItem *EmployeesTBL1;
        TMenuItem *OwnersTBL1;
        TMenuItem *PartsTBL1;
        TMenuItem *ServicesTBL1;
        TIntegerField *EmployeeTBLID;
        TIBStringField *EmployeeTBLFIRST_NAME;
        TIBStringField *EmployeeTBLFAM_NAME;
        TIBStringField *EmployeeTBLSERVICE_PHONE_NUMBER;
        TIBStringField *EmployeeTBLE_MAIL;
        TIntegerField *EmployeeTBLPOSSITION_ID;
        TIBStringField *EmployeeTBLUSER_PASSWORD;
        TIBStringField *EmployeeTBLUSERNAME;
        TIBTable *PossitionTBL;
        TDataSource *PossitionDS;
        TStringField *EmployeeTBLPOSSITION;
        TIBTable *VehicleNomTBL;
        TDataSource *VehicleNomDS;
        TIBTable *OwnerTBL;
        TDataSource *OwnerDS;
        TIBTable *BrandTBL;
        TIBTable *RepairServiceTBL;
        TDataSource *RepairServiceDS;
        TDataSource *BrandDS;
        TDataSource *ServiceDS;
        TDataSource *CategoryDS;
        TDataSource *EngineTypeDS;
        TIBTable *ServiceTBL;
        TIBTable *CategoryTBL;
        TIBTable *EngineTypeTBL;
        TIBTable *ItemTBL;
        TIBTable *ItemNomTBL;
        TIBTable *ManufacturerTBL;
        TIBTable *MesureTBL;
        TIBTable *VehicleTypeTBL;
        TDataSource *ItemDS;
        TDataSource *MesureDS;
        TDataSource *VehicleTypeDS;
        TDataSource *ItemNomDS;
        TDataSource *ManufacturerDS;
        TIntegerField *VehicleTBLID;
        TIntegerField *VehicleTBLOWNER_ID;
        TIntegerField *VehicleTBLVEHICLE_NOMENCLATURE_ID;
        TIBStringField *VehicleTBLCHASSIS_NUMBER;
        TIBStringField *VehicleTBLFRAME_NUMBER;
        TIntegerField *VehicleNomTBLID;
        TIntegerField *VehicleNomTBLBRAND_ID;
        TIBStringField *VehicleNomTBLMODEL;
        TIntegerField *VehicleNomTBLCATEGORY_ID;
        TIntegerField *VehicleNomTBLENGINE_TYPE_ID;
        TIntegerField *VehicleNomTBLTYPE_VEHICLE_ID;
        TIBBCDField *VehicleNomTBLENGINE_VOLUME;
        TIBStringField *VehicleNomTBLLOADABILITY;
        TIntegerField *VehicleNomTBLAXLES_NUMBER;
        TIntegerField *VehicleNomTBLSEATS_NUMBER;
        TStringField *VehicleNomTBLBRAND_NAME;
        TStringField *VehicleNomTBLCATEGORY_NAME;
        TStringField *VehicleNomTBLENGINE_NAME;
        TStringField *VehicleNomTBLTYPE_NAME;
        TStringField *VehicleTBLOWNER_NAME;
        TStringField *VehicleTBLVEHICLE_BRAND_NAME;
        TStringField *VehicleTBLVEHICLE_MODEL_NAME;
        TStringField *VehicleTBLVEHICLE_CATEGORY_NAME;
        TStringField *VehicleTBLVEHICLE_ENGINE_NAME;
        TStringField *VehicleTBLVEHICLE_TYPE_NAME;
        TMenuItem *BrandTBL1;
        TMenuItem *N1;
        TMenuItem *N2;
        TMenuItem *N3;
        TMenuItem *N4;
        TMenuItem *N5;
        TMenuItem *N6;
        TIntegerField *OwnerTBLID;
        TIBStringField *OwnerTBLNAME;
        TLargeintField *OwnerTBLPHONE_NUMBER;
        TIBStringField *OwnerTBLADDRESS;
        TIBStringField *OwnerTBLE_MAIL;
        TIBStringField *OwnerTBLMOL;
        TIBStringField *OwnerTBLBUL_EGN;
        TIntegerField *ItemNomTBLID;
        TIBStringField *ItemNomTBLNAME;
        TIntegerField *ItemNomTBLMANUFACTURER_ID;
        TIntegerField *ItemNomTBLMEASURE_ID;
        TStringField *ItemNomTBLMANUFACTURER_NAME;
        TStringField *ItemNomTBLMESURE_NAME;
        TIntegerField *ServiceTBLID;
        TIBStringField *ServiceTBLNAME;
        TIntegerField *BrandTBLID;
        TIBStringField *BrandTBLNAME;
        TIntegerField *VehicleTypeTBLID;
        TIBStringField *VehicleTypeTBLNAME;
        TIntegerField *EngineTypeTBLID;
        TIBStringField *EngineTypeTBLNAME;
        TIntegerField *ManufacturerTBLID;
        TIBStringField *ManufacturerTBLNAME;
        TIntegerField *MesureTBLID;
        TIBStringField *MesureTBLNAME;
        TIBStringField *MesureTBLABBREVIATION;
        TIntegerField *PossitionTBLID;
        TIBStringField *PossitionTBLNAME;
        TIBStoredProc *VehicleSP;
        TMenuItem *N7;
        TIBStoredProc *RepairSP;
        TIBStoredProc *RShopSP;
        TIBStoredProc *ServiceSP;
        TIBStoredProc *RepairServiceSP;
        TIBStoredProc *EmployeeSP;
        TIBStoredProc *OwnerSP;
        TIBStoredProc *VehicleNomSP;
        TIBStoredProc *PossitionSP;
        TIBStoredProc *CategorySP;
        TIBStoredProc *BrandSP;
        TIBStoredProc *EngineTypeSP;
        TIBStoredProc *ItemSP;
        TIBStoredProc *ItemNomSP;
        TIBStoredProc *MesureSP;
        TIBStoredProc *ManufacturerSP;
        TIBStoredProc *VehicleTypeSP;
        TIntegerField *RepairServiceTBLID;
        TIntegerField *RepairServiceTBLREPAIR_ID;
        TIntegerField *RepairServiceTBLSERVICE_ID;
        TIBBCDField *RepairServiceTBLTOTAL_PRICE;
        TIntegerField *ItemTBLID;
        TIBBCDField *ItemTBLPRICE;
        TIBBCDField *ItemTBLQUANTITY;
        TIntegerField *ItemTBLITEM_NOMENCLATURE_ID;
        TIntegerField *ItemTBLSERVICE_ID;
        TStringField *ItemTBLMANUFACTURER_NAME_ITEM;
        TStringField *ItemTBLMEASURE_NAME_ITEM;
        TMenuItem *N8;
        TDataSource *AllServicesDS;
        TIBTable *AllServiceTBL;
        TStringField *RepairServiceTBLSERVICE;
        TIntegerField *RepairTBLID;
        TIBStringField *RepairTBLNOTE;
        TDateField *RepairTBLACCPETANCE_DATE;
        TDateField *RepairTBLCOMPLETION_DATE;
        TIntegerField *RepairTBLEMPLOYEE_ID;
        TIntegerField *RepairTBLREPAIR_SHOP_ID;
        TIntegerField *RepairTBLVEHICLE_ID;
        TIBStringField *RepairTBLACCEPTED_THE_VEHICLE;
        TIBStringField *VehicleTBLREGISTRATION_NUMBER;
        TDateField *VehicleTBLREGISTRATION_DATE;
        TDateField *VehicleTBLPRODUCTION_YEAR;
        TIntegerField *CategoryTBLID;
        TIBStringField *CategoryTBLNAME;
        TIntegerField *AllServiceTBLID;
        TIBStringField *AllServiceTBLNAME;
        TIBStringField *EmployeeTBLPHONE_NUMBER;
        TIntegerField *RShopTBLID;
        TIBStringField *RShopTBLNAME;
        TIBStringField *RShopTBLADDRESS;
        TStringField *ItemTBLNAME;
        TMenuItem *N9;
        TMenuItem *N10;
        TIBQuery *LogInQuery;
        TIBQuery *RepairCountQuery;
        TDataSource *RepairCountDS;
        TIBStringField *RepairCountQueryNAME;
        TIntegerField *RepairCountQueryCNT;
        TIBQuery *ServiceCountQuery;
        TDataSource *ServiceCountDS;
        TIBStringField *ServiceCountQueryNAME;
        TIntegerField *ServiceCountQueryCNT;
        TIBQuery *SumQuery;
        TIBQuery *PriceQuery;
        TDataSource *PriceDS;
        TIBStringField *PriceQueryNAME;
        TIBBCDField *PriceQueryMAXI;
        TIBBCDField *PriceQuerySUMM;
        TIBQuery *repair_service_delete_query;
        TStringField *RepairTBLREPAIR_SHOP_NAME;
        TStringField *RepairTBLEMPLOYEE_NAME;
        TStringField *RepairTBLEMPLOYEE_POSSITION;
        TIBQuery *ReferenceRepairQuery;
        TDataSource *ReferenceRepairDS;
        TDataSource *ReferenceItemDS;
        TMenuItem *N11;
        TDateField *ReferenceRepairQueryACCPETANCE_DATE;
        TDateField *ReferenceRepairQueryCOMPLETION_DATE;
        TIBStringField *ReferenceRepairQueryACCEPTED_THE_VEHICLE;
        TIBStringField *ReferenceRepairQueryREGISTRATION_NUMBER;
        TIBStringField *ReferenceRepairQueryNAME;
        TIBStringField *ReferenceRepairQueryNAME1;
        TIBStringField *ReferenceRepairQueryNOTE;
        TIBStringField *ReferenceRepairQueryNAME2;
        TIBQuery *ReferenceItemQuery;
        TIBStringField *ReferenceItemQueryNAME;
        TIBBCDField *ReferenceItemQueryPRICE;
        TIBBCDField *ReferenceItemQueryQUANTITY;
        TDateField *ReferenceItemQueryCOMPLETION_DATE;
        TIBStringField *ReferenceItemQueryREGISTRATION_NUMBER;
        TIBStringField *ReferenceItemQueryNAME3;
        TIBStringField *ReferenceItemQueryNAME4;
        TIBStringField *ReferenceItemQueryNAME1;
        TIBStringField *ReferenceItemQueryNAME2;
        TDateField *ReferenceItemQueryACCPETANCE_DATE;
        TMenuItem *N12;
        TMenuItem *N13;
        TMenuItem *N14;
        void __fastcall EmployeesTBL1Click(TObject *Sender);
        void __fastcall OwnersTBL1Click(TObject *Sender);
        void __fastcall PartsTBL1Click(TObject *Sender);
        void __fastcall ServicesTBL1Click(TObject *Sender);
        void __fastcall BrandTBL1Click(TObject *Sender);
        void __fastcall N1Click(TObject *Sender);
        void __fastcall N6Click(TObject *Sender);
        void __fastcall N2Click(TObject *Sender);
        void __fastcall N3Click(TObject *Sender);
        void __fastcall N4Click(TObject *Sender);
        void __fastcall N5Click(TObject *Sender);
        void __fastcall VehicleTBLBeforePost(TDataSet *DataSet);
        void __fastcall N7Click(TObject *Sender);
        void __fastcall RepairTBLBeforePost(TDataSet *DataSet);
        void __fastcall N8Click(TObject *Sender);
        void __fastcall RepairServiceTBLBeforePost(TDataSet *DataSet);
        void __fastcall ItemTBLBeforePost(TDataSet *DataSet);
        void __fastcall About1Click(TObject *Sender);
        void __fastcall BrandTBLBeforePost(TDataSet *DataSet);
        void __fastcall VehicleNomTBLBeforePost(TDataSet *DataSet);
        void __fastcall CategoryTBLBeforePost(TDataSet *DataSet);
        void __fastcall VehicleTypeTBLBeforePost(TDataSet *DataSet);
        void __fastcall EngineTypeTBLBeforePost(TDataSet *DataSet);
        void __fastcall OwnerTBLBeforePost(TDataSet *DataSet);
        void __fastcall AllServiceTBLBeforePost(TDataSet *DataSet);
        void __fastcall MesureTBLBeforePost(TDataSet *DataSet);
        void __fastcall ManufacturerTBLBeforePost(TDataSet *DataSet);
        void __fastcall ItemNomTBLBeforePost(TDataSet *DataSet);
        void __fastcall PossitionTBLBeforePost(TDataSet *DataSet);
        void __fastcall EmployeeTBLBeforePost(TDataSet *DataSet);
        void __fastcall RShopTBLBeforePost(TDataSet *DataSet);
        void __fastcall ItemTBLAfterPost(TDataSet *DataSet);
        void __fastcall N10Click(TObject *Sender);
        void __fastcall Export1Click(TObject *Sender);
        void __fastcall N9Click(TObject *Sender);
        void __fastcall N11Click(TObject *Sender);
        void __fastcall N13Click(TObject *Sender);
        void __fastcall N14Click(TObject *Sender);
private:	// User declarations
public:		// User declarations
        __fastcall TDM(TComponent* Owner);
};
//---------------------------------------------------------------------------
extern PACKAGE TDM *DM;
//---------------------------------------------------------------------------
#endif
